name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: make
      run: make

  test:
    runs-on: windows-latest
    needs: [ build ]
    steps:
    - name: make check
      run: make check
