name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Build
      run: make
    - name: Upload workspace artifact
      uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: ${{github.workspace}}
    
  test:
    runs-on: windows-latest
    needs: [ build ]
    steps:
    - name: Download workspace artifact
      uses: actions/download-artifact@v2
      with:
        name: workspace
    - name: Check
      run: make check
  
  clear:
    runs-on: windows-latest
    needs: [ build, test ]
    steps:
    - name: Delete workflow artifacts
      uses: GeekyEggo/delete-artifact@v1.0.0
      with:
        name: workspace
        failOnError: false
